function createdoublearrow(figure1,P_color,E_color,Qin_color,Qout_color)
%CREATEDOUBLEARROW(FIGURE1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 13-Apr-2017 18:28:03

% Precipitation arrow
annotation(figure1,'doublearrow',[0.9225589225589240 0.922558922558924],...
    [0.856697819314642 0.630841121495327],'Color',P_color,'LineWidth',2);

% inflow arrow
annotation(figure1,'doublearrow',[0.922558922558924 0.922558922558924],...
    [0.61993769470405 0.523364485981308],'Color',Qin_color,'LineWidth',2);

% Evaporation arrow
annotation(figure1,'doublearrow',[0.922558922558924 0.922558922558924],...
    [0.513018691588785 0.417445482866044],'Color',Qout_color,'LineWidth',2);

% outflow arrow
annotation(figure1,'doublearrow',[0.922558922558924 0.922558922558924],...
    [0.40709968847352 0.172897196261682],'Color',E_color,'LineWidth',2);

% Evaporation arrow





